WITH CleanedData AS (
    SELECT
        a.GROUP_NAME,
		a.ALIAS_NAME,
		a.INSTRUMENT,
        r.ANALYSIS,
        r.NAME,
        t.VERSION,
        CAST(REPLACE(REPLACE(c.CLAMP_LOW, ',', '.'), '<', '') AS FLOAT) AS CLAMP_LOW_CLEAN,
        r.ENTERED_ON,
        u.DISPLAY_STRING
    FROM result r
    INNER JOIN test t ON r.TEST_NUMBER = t.TEST_NUMBER
    INNER JOIN analysis a ON a.NAME = t.ANALYSIS AND a.VERSION = t.VERSION
    INNER JOIN component c ON c.ANALYSIS = r.ANALYSIS AND c.NAME = r.NAME AND c.VERSION = t.VERSION
    INNER JOIN UNITS u on u.UNIT_CODE = r.UNITS
    WHERE
        a.GROUP_NAME NOT IN ('GENETICA', 'OBSOLETE')
        AND c.CLAMP_LOW IS NOT NULL
)
SELECT
    GROUP_NAME,
    ANALYSIS,
	  ALIAS_NAME,
	  INSTRUMENT,
    NAME,
    VERSION,
    CLAMP_LOW_CLEAN,
    DISPLAY_STRING,
    MIN(ENTERED_ON) AS MIN_DATE,
    MAX(ENTERED_ON) AS MAX_DATE
FROM CleanedData
GROUP BY
  GROUP_NAME,
  ANALYSIS,
	ALIAS_NAME,
	INSTRUMENT,
  NAME,
  VERSION,
  CLAMP_LOW_CLEAN,
  DISPLAY_STRING
ORDER BY
	GROUP_NAME,
  ANALYSIS,
  NAME,
  VERSION;
